issue334 - Added support for JSON logging via -j command line option
missionpinball/mpf-mc pull request #335
Opened 2018-05-15 07:42 UTC by muffler-aus

Initial PR to allow JSON logging as per https://github.com/missionpinball/mpf-mc/issues/334

2018-05-15 23:05 UTC, jabdoa2 requested changes

2018-05-15 23:05 UTC, jabdoa2 commented on mpfmc/commands/mc.py
> +from mpfmc.commands.logging_formatters import JSONFormatter
Would it be possible to use mpf.commands.logging_formatters? Or do we have to duplicate that here?

2018-05-15 23:50 UTC, muffler-aus commented on mpfmc/commands/mc.py
> +from mpfmc.commands.logging_formatters import JSONFormatter
yeah, that should be fine. I was thinking of the two repos as unique. I will update the PR and Remove the duplication. 👍

2018-05-15 23:51 UTC, jabdoa2 commented on mpfmc/commands/mc.py
> +from mpfmc.commands.logging_formatters import JSONFormatter
mpf-mc will always require mpf so it is fine this way (not the other way around though)

2018-05-15 23:55 UTC, muffler-aus commented on mpfmc/commands/mc.py
> +from mpfmc.commands.logging_formatters import JSONFormatter
Updated :)

2018-05-16 00:18 UTC, jabdoa2 approved these changes

2018-05-16 08:59 UTC, merged

2018-05-16 08:59 UTC, jabdoa2 commented
Thanks!