Throws Error when attempting to define more than one default display
missionpinball/mpf-mc pull request #376
Opened 2019-06-25 03:59 UTC by GranolaDaniel

Fixes issue: https://github.com/missionpinball/mpf/issues/1315

2019-06-25 06:12 UTC, jabdoa2 requested changes
Thanks for your effort! Looks good. Just some minor nitpicks.

2019-06-25 06:12 UTC, jabdoa2 commented on mpfmc/uix/display.py
> +                elif 'default' in self.mc.targets:
This can be simplified. Since the condition of if and elif is the same just use "else".

2019-06-25 06:12 UTC, jabdoa2 commented on mpfmc/uix/display.py
> +
Please remove those space characters. They make the linter unhappy:

> Messages
> ========
> mpfmc/uix/display.py
>   Line: 142
>     pep8: W293 / blank line contains whitespace (col 1)
>   Line: 153
>     pep8: E501 / line too long (218 > 120 characters) (col 121)

2019-06-25 06:12 UTC, jabdoa2 commented on mpfmc/uix/display.py
> +                    raise AssertionError('Multiple displays have been set as the default. Please choose a single display to default to (\"{}\" is currently set as the default).'.format(self.mc.target
Please break the line. More than 120 characters make the linter unhappy. https://travis-ci.org/missionpinball/mpf-mc/jobs/550076932#L5075

2019-06-25 17:19 UTC, jabdoa2 commented
One more:
```
Messages
========
mpfmc/uix/display.py
  Line: None
    pep8: E101 / indentation contains mixed spaces and tabs (col 1)
  Line: 153
    pep8: W191 / indentation contains tabs (col 1)
```

I can also fix that later if you want.

2019-06-25 17:20 UTC, jabdoa2 approved these changes

2019-06-25 19:51 UTC, GranolaDaniel commented
> One more:
> 
> ```
> Messages
> ========
> mpfmc/uix/display.py
>   Line: None
>     pep8: E101 / indentation contains mixed spaces and tabs (col 1)
>   Line: 153
>     pep8: W191 / indentation contains tabs (col 1)
> ```
> 
> I can also fix that later if you want.

I believe that I've switched that line back to spaced indentation. Please let me know if you have any feedback, and thank you for the guidance!

2019-06-25 20:57 UTC, jabdoa2 commented
Now it complains about long lines again:

 mpfmc/uix/display.py Line: 153 pep8: E501 / line too long (129 > 120 characters) (col 121)

2019-06-25 21:19 UTC, jabdoa2 commented
Now it complains about long lines again:

 mpfmc/uix/display.py Line: 153 pep8: E501 / line too long (129 > 120 characters) (col 121)

2019-06-26 05:58 UTC, jabdoa2 commented on mpfmc/uix/display.py
> +                        display to default to (\"{}\" is currently set as the default).'.format(
Python would like this one indented as much as the braket in the previous line. You can run the linter locally if you want. Installing it: pip install prospector. Running it inside the mpf folder: prospector

```
mpfmc/uix/display.py
  Line: 154
    pep8: E126 / continuation line over-indented for hanging indent (col 29)
```

2019-06-26 13:01 UTC, GranolaDaniel commented on mpfmc/uix/display.py
> +                        display to default to (\"{}\" is currently set as the default).'.format(
Thanks for pointing me to the linter! I've just submitted a new PR after running it. Let me know if anything else looks off.

2019-06-30 13:06 UTC, merged

2019-06-30 13:06 UTC, jabdoa2 commented
Thanks for all the effort!